// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qblxtelprbvangxxjdxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFibHh0ZWxwcmJ2YW5neHhqZHhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNjIwMTYsImV4cCI6MjA3MzgzODAxNn0.sF4NyyhNl6B0vbxsXg5ofiW-byj-edOAp60cmkdgoVI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});